## K Fold Cross Validation

In [1]:

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier



In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
from sklearn.datasets import load_digits
digits=load_digits()

In [11]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [13]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=0.3)

In [26]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\Afzal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [27]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9796296296296296

In [28]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9555555555555556

# to implement many algrothim in one code   like,logastic,svc,randomforestclassifier....,

In [39]:
def get_score(model,X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [40]:
get_score(LogisticRegression(),X_train, X_test, y_train, y_test)

C:\Users\Afzal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9537037037037037

In [41]:
get_score(SVC(),X_train, X_test, y_train, y_test)

0.9796296296296296

In [42]:
get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test)

0.9648148148148148

### K FOLD

In [35]:
from sklearn.model_selection import KFold
k=KFold(n_splits=3)
k

KFold(n_splits=3, random_state=None, shuffle=False)

In [36]:
for train_index,test_index in k.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)
    


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


##  this(long code no need) is for demo  for whole code their is one function in sklearn cross_val_score
## BY Using k fold we will evulate perfomance of all the three algrothm

In [53]:
from sklearn.model_selection import StratifiedKFold
fold=StratifiedKFold(n_splits=3)

score_logestic=[]
score_svm=[]
score_rf=[]

for train_index,test_index in fold.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],\
    digits.target[test_index]
    
    
    score_logestic.append(get_score(LogisticRegression(),X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train, X_test, y_train, y_test))







C:\Users\Afzal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Afzal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [54]:
score_logestic

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [55]:

score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [56]:

score_rf

[0.9298831385642737, 0.9532554257095158, 0.9198664440734557]

## cross_val_score

In [57]:
from sklearn.model_selection import cross_val_score


In [58]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\Afzal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Afzal\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [59]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [61]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=5)  #it will give five 

array([0.92777778, 0.91944444, 0.95821727, 0.9637883 , 0.92200557])

In [62]:
score1=cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=10)
np.average(score1)

0.9488081936685289

In [63]:
score2=cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=20)
np.average(score2)

0.9693320848938827

In [64]:
score3=cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=30)
np.average(score3)

0.9721374764595103